# docker-compose.yml
version: '3.8'
networks:
  minecraft-net:
    driver: bridge
services:
  velocity:
    image: itzg/bungeecord
    container_name: velocity-proxy
    restart: unless-stopped
    ports: ["25565:25565"]
    volumes: ["./velocity-data:/server"]
    environment:
      TYPE: "VELOCITY"
      TZ: "America/Sao_Paulo"
    networks: ["minecraft-net"]
  sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    volumes: ["./sobrevivencia-data:/data"]
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "8G"
      BUNGEE_CORD: "TRUE"
      ONLINE_MODE: "FALSE"
      PLUGINS: "https://jd.viaversion.com"
    networks: ["minecraft-net"]