# A linha 'version' foi removida para seguir as práticas modernas.
networks:
  minecraft-net:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    
    # Expomos a porta do servidor de jogo diretamente para o mundo exterior.
    ports:
      - "25565:25565"

    volumes:
      # Usamos um diretório local para persistir os dados do mundo.
      - ./sobrevivencia-data:/data
      
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "10G"
      
      # O servidor agora fará sua própria autenticação (modo premium).
      ONLINE_MODE: "true"
      
    networks:
      - "minecraft-net"