version: "3.8"

networks:
  minecraft-net:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      # mundo + dados persistentes
      - ./sobrevivencia-data:/data

      # todos os configs do Paper (server.properties, paper-global.yml, spigot.yml, forwarding.secret)
      - ./paper/configs:/config:ro

      # plugins baixados pelo CI
      - ./paper/plugins:/data/plugins:ro

    environment:
      EULA:               "TRUE"
      TYPE:               "PAPER"
      MEMORY:             "10G"
      ONLINE_MODE:        "false"
      VELOCITY_ENABLED:   "true"
      VELOCITY_SECRET_FILE: "/config/forwarding.secret"

    networks:
      - minecraft-net
    depends_on:
      - velocity-proxy

  velocity-proxy:
    image: itzg/mc-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      # configurações e secret do proxy
      - ./velocity:/config:ro

      # plugins do proxy (se houver)
      - ./velocity/plugins:/config/plugins:ro

    environment:
      TYPE:   "VELOCITY"
      MEMORY: "1G"
    networks:
      - minecraft-net
