version: "3.8"

networks:
  minecraft-net:
    driver: bridge

services:
  velocity-proxy:
    image: itzg/mc-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      - ./velocity/velocity.toml:/config/velocity.toml
      - ./velocity/forwarding.secret:/config/forwarding.secret
    environment:
      TYPE: VELOCITY
      VELOCITY_VERSION: "latest"
      MEMORY: "1G"
    networks:
      - minecraft-net

  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      - ./sobrevivencia-data:/data
      - ./paper/configs/server.properties:/config/server.properties
      - ./paper/configs/paper-global.yml:/config/paper-global.yml
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "10G"
      ONLINE_MODE: "false"
      VELOCITY_ENABLED: "true"
      VELOCITY_SECRET_FILE: "/config/forwarding.secret"
    networks:
      - minecraft-net
    depends_on:
      - velocity-proxy
