version: "3.8"

networks:
  minecraft-net:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      # mundo e dados persistentes
      - ./sobrevivencia-data:/data

      # configs gerados pelo CI
      - ./terraform/paper/configs/server.properties:/config/server.properties
      - ./terraform/paper/configs/paper-global.yml:/config/paper-global.yml

      # segredo Velocity gerado pelo CI
      - ./terraform/velocity/forwarding.secret:/config/forwarding.secret

      # plugins baixados pelo CI via scripts/fetch-plugins.sh
      - ./terraform/paper/plugins:/data/plugins

    environment:
      EULA:               "TRUE"
      TYPE:               "PAPER"
      MEMORY:             "10G"
      ONLINE_MODE:        "false"
      VELOCITY_ENABLED:   "true"
      VELOCITY_SECRET_FILE: "/config/forwarding.secret"

    networks:
      - minecraft-net
    depends_on:
      - velocity-proxy

  velocity-proxy:
    image: itzg/mc-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      # toda config do proxy (toml + secret)
      - ./terraform/velocity:/config

      # plugins do proxy, caso use algum
      - ./terraform/velocity/plugins:/config/plugins

    environment:
      TYPE:   "VELOCITY"
      MEMORY: "1G"
    networks:
      - minecraft-net
