networks:
  minecraft-net:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      - ./sobrevivencia-data:/data
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "10G"
      ONLINE_MODE: "true"
      VELOCITY_ENABLED: "true"
      VELOCITY_SECRET_FILE: "/velocity/forwarding.secret"
    networks:
      - minecraft-net
    depends_on:
      - velocity-proxy

  velocity-proxy:
    image: itzg/mc-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      - ./velocity:/config
    environment:
      TYPE: "VELOCITY"
      VELOCITY_VERSION: "latest"
      VELOCITY_BUILD_ID: "latest"
    networks:
      - minecraft-net
