networks:
  minecraft-net:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./sobrevivencia-data:/data
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "10G"
      ONLINE_MODE: "true"
    networks:
      - minecraft-net

  velocity-proxy:
    image: itzg/bungeecord
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25577:25577"
    volumes:
      - ./velocity:/config
    environment:
      TYPE: VELOCITY
    networks:
      - minecraft-net
