version: "3.8"

networks:
  minecraft-net:
    driver: bridge

services:
  mc-sobrevivencia:
    image: itzg/minecraft-server
    container_name: mc-sobrevivencia
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      # mundo e dados
      - ./sobrevivencia-data:/data

      # pasta única de configs (server.properties, paper-global.yml, forwarding.secret, etc)
      - ./terraform/paper/configs:/config

      # plugins baixados pelo CI
      - ./terraform/paper/plugins:/data/plugins:ro

    environment:
      EULA:               "TRUE"
      TYPE:               "PAPER"
      MEMORY:             "10G"
      ONLINE_MODE:        "false"
      VELOCITY_ENABLED:   "true"
      VELOCITY_SECRET_FILE: "/config/forwarding.secret"

    networks:
      - minecraft-net
    depends_on:
      - velocity-proxy

  velocity-proxy:
    image: itzg/mc-proxy:latest
    container_name: velocity-proxy
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      # apenas o folder de config do proxy (velocity.toml + plugins)
      - ./terraform/velocity:/config:ro

    environment:
      TYPE:   "VELOCITY"
      MEMORY: "1G"
    networks:
      - minecraft-net
