[servers]
sobrevivencia = "sobrevivencia:25565"
try = ["sobrevivencia"]

[forced-hosts]
# A pipeline irá substituir este placeholder pelo IP real.
"__SERVER_IP__:25565" = ["sobrevivencia"]

[advanced]
player-info-forwarding-mode = "modern"

[metrics]
enabled = false