# config/velocity.toml
[servers]
sobrevivencia = "sobrevivencia:25565"
try = ["sobrevivencia"]
[forced-hosts]
# Usaremos um placeholder que a pipeline irá substituir
"__SERVER_IP__:25565" = ["sobrevivencia"]
[advanced]
player-info-forwarding-mode = "modern"
[metrics]
enabled = false