# Usa a imagem oficial como base.
FROM papermc/velocity:latest
# Define o diretório de trabalho.
WORKDIR /app
# Copia os nossos ficheiros de configuração para dentro da imagem.
COPY velocity.toml .
COPY forwarding.secret .