# Usa a imagem oficial como base.
FROM papermc/paper:latest
# Define o diretório de trabalho.
WORKDIR /app
# Copia os nossos ficheiros de configuração para dentro da imagem.
COPY server.properties .
COPY config/paper-global.yml config/